# compose.yml:jeff
#
# Docker compose container for iperf3 server-side daemon
#
---

networks:
  nginx-proxy:
    attachable: true
    driver: overlay
    external: true

services:

  iperf3:
    restart: unless-stopped
    user: nobody
    command: ["--verbose", "--server"]
    environment:
      - TZ=UTC
    networks:
      - nginx-proxy
    ports:
      - 5201:5201/udp
    image: networkstatic/iperf3:latest
    container_name: iperf3-1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro

